"""create canonical data model

Revision ID: ac38bbf33d78
Revises:
Create Date: 2026-07-22 06:01:09.307115+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "ac38bbf33d78"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "compliance_rules",
        sa.Column("rule_code", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("applicable_equipment_class", sa.String(length=120), nullable=True),
        sa.Column("applicable_criticality", sa.String(length=40), nullable=True),
        sa.Column("rule_type", sa.String(length=80), nullable=False),
        sa.Column("configuration_json", sa.JSON(), server_default="{}", nullable=False),
        sa.Column("severity", sa.String(length=40), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "applicable_criticality in ('low', 'medium', 'high', 'safety_critical') or applicable_criticality is null",
            name="ck_compliance_rules_criticality",
        ),
        sa.CheckConstraint(
            "rule_type in ('document_required', 'inspection_interval', 'rca_required', 'custom')",
            name="ck_compliance_rules_type",
        ),
        sa.CheckConstraint(
            "severity in ('informational', 'low', 'medium', 'high', 'critical', 'unknown')",
            name="ck_compliance_rules_severity",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rule_code", name="uq_compliance_rules_code"),
    )
    op.create_index("ix_compliance_rules_enabled", "compliance_rules", ["enabled"], unique=False)
    op.create_index("ix_compliance_rules_type", "compliance_rules", ["rule_type"], unique=False)
    op.create_table(
        "documents",
        sa.Column("document_code", sa.String(length=120), nullable=False),
        sa.Column("original_filename", sa.String(length=512), nullable=False),
        sa.Column("stored_filename", sa.String(length=512), nullable=True),
        sa.Column("file_type", sa.String(length=80), nullable=True),
        sa.Column("mime_type", sa.String(length=160), nullable=True),
        sa.Column("source_type", sa.String(length=120), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("parser_name", sa.String(length=120), nullable=True),
        sa.Column("parse_status", sa.String(length=40), nullable=False),
        sa.Column("parse_warnings_json", sa.JSON(), server_default="[]", nullable=False),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "parse_status in ('registered', 'pending', 'processing', 'completed', 'completed_with_warnings', 'failed')",
            name="ck_documents_parse_status",
        ),
        sa.CheckConstraint(
            "file_size_bytes is null or file_size_bytes >= 0", name="ck_documents_size"
        ),
        sa.CheckConstraint("page_count is null or page_count >= 0", name="ck_documents_page_count"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_documents_document_code", "documents", ["document_code"], unique=True)
    op.create_index("ix_documents_parse_status", "documents", ["parse_status"], unique=False)
    op.create_index("ix_documents_sha256", "documents", ["sha256"], unique=True)
    op.create_table(
        "equipment",
        sa.Column("equipment_tag", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("equipment_class", sa.String(length=120), nullable=True),
        sa.Column("site", sa.String(length=120), nullable=True),
        sa.Column("system", sa.String(length=120), nullable=True),
        sa.Column("criticality", sa.String(length=40), nullable=False),
        sa.Column("manufacturer", sa.String(length=160), nullable=True),
        sa.Column("model", sa.String(length=160), nullable=True),
        sa.Column("serial_number", sa.String(length=160), nullable=True),
        sa.Column("operational_status", sa.String(length=40), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), server_default="{}", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "criticality in ('low', 'medium', 'high', 'safety_critical')",
            name="ck_equipment_criticality",
        ),
        sa.CheckConstraint(
            "operational_status in ('active', 'standby', 'under_maintenance', 'out_of_service', 'retired', 'unknown')",
            name="ck_equipment_operational_status",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_equipment_class", "equipment", ["equipment_class"], unique=False)
    op.create_index("ix_equipment_criticality", "equipment", ["criticality"], unique=False)
    op.create_index("ix_equipment_equipment_tag", "equipment", ["equipment_tag"], unique=True)
    op.create_index("ix_equipment_site_system", "equipment", ["site", "system"], unique=False)
    op.create_table(
        "ingestion_jobs",
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("total_files", sa.Integer(), nullable=False),
        sa.Column("processed_files", sa.Integer(), nullable=False),
        sa.Column("failed_files", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata_json", sa.JSON(), server_default="{}", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status in ('pending', 'processing', 'completed', 'completed_with_errors', 'failed')",
            name="ck_ingestion_jobs_status",
        ),
        sa.CheckConstraint("failed_files >= 0", name="ck_ingestion_jobs_failed_files"),
        sa.CheckConstraint(
            "processed_files + failed_files <= total_files", name="ck_ingestion_jobs_count_bounds"
        ),
        sa.CheckConstraint("processed_files >= 0", name="ck_ingestion_jobs_processed_files"),
        sa.CheckConstraint("total_files >= 0", name="ck_ingestion_jobs_total_files"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_ingestion_jobs_started_at", "ingestion_jobs", ["started_at"], unique=False)
    op.create_index("ix_ingestion_jobs_status", "ingestion_jobs", ["status"], unique=False)
    op.create_table(
        "components",
        sa.Column("equipment_id", sa.Uuid(), nullable=False),
        sa.Column("component_tag", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("component_type", sa.String(length=120), nullable=True),
        sa.Column("manufacturer", sa.String(length=160), nullable=True),
        sa.Column("model", sa.String(length=160), nullable=True),
        sa.Column("serial_number", sa.String(length=160), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), server_default="{}", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["equipment_id"], ["equipment.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("equipment_id", "component_tag", name="uq_component_equipment_tag"),
    )
    op.create_index("ix_components_component_type", "components", ["component_type"], unique=False)
    op.create_index("ix_components_equipment_id", "components", ["equipment_id"], unique=False)
    op.create_table(
        "document_pages",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("text_content", sa.String(), nullable=True),
        sa.Column("rendered_image_path", sa.String(length=1024), nullable=True),
        sa.Column("width", sa.Float(), nullable=True),
        sa.Column("height", sa.Float(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), server_default="{}", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "height is null or height > 0", name="ck_document_pages_height_positive"
        ),
        sa.CheckConstraint("page_number > 0", name="ck_document_pages_page_positive"),
        sa.CheckConstraint("width is null or width > 0", name="ck_document_pages_width_positive"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "page_number", name="uq_document_pages_document_page"),
    )
    op.create_index(
        "ix_document_pages_document_id", "document_pages", ["document_id"], unique=False
    )
    op.create_table(
        "extraction_runs",
        sa.Column("document_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("extractor_name", sa.String(length=160), nullable=False),
        sa.Column("extractor_version", sa.String(length=120), nullable=True),
        sa.Column("model_provider", sa.String(length=120), nullable=True),
        sa.Column("model_name", sa.String(length=160), nullable=True),
        sa.Column("prompt_version", sa.String(length=120), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), server_default="{}", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status in ('pending', 'processing', 'completed', 'completed_with_errors', 'failed')",
            name="ck_extraction_runs_status",
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_extraction_runs_document_id", "extraction_runs", ["document_id"], unique=False
    )
    op.create_index(
        "ix_extraction_runs_extractor",
        "extraction_runs",
        ["extractor_name", "extractor_version"],
        unique=False,
    )
    op.create_index("ix_extraction_runs_status", "extraction_runs", ["status"], unique=False)
    op.create_table(
        "chunks",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("document_page_id", sa.Uuid(), nullable=True),
        sa.Column("equipment_id", sa.Uuid(), nullable=True),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("chunk_kind", sa.String(length=80), nullable=True),
        sa.Column("section_path", sa.String(length=1024), nullable=True),
        sa.Column("text_content", sa.String(), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("citation_label", sa.String(length=120), nullable=True),
        sa.Column("bounding_box_json", sa.JSON(), nullable=True),
        sa.Column("parser_metadata_json", sa.JSON(), server_default="{}", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("token_count is null or token_count >= 0", name="ck_chunks_token_count"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["document_page_id"], ["document_pages.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["equipment_id"], ["equipment.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "chunk_index", name="uq_chunks_document_index"),
    )
    op.create_index("ix_chunks_chunk_kind", "chunks", ["chunk_kind"], unique=False)
    op.create_index("ix_chunks_document_id", "chunks", ["document_id"], unique=False)
    op.create_index("ix_chunks_document_page_id", "chunks", ["document_page_id"], unique=False)
    op.create_index("ix_chunks_equipment_id", "chunks", ["equipment_id"], unique=False)
    op.create_table(
        "citations",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("document_page_id", sa.Uuid(), nullable=True),
        sa.Column("chunk_id", sa.Uuid(), nullable=True),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("evidence_excerpt", sa.String(), nullable=True),
        sa.Column("bounding_box_json", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["chunk_id"], ["chunks.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["document_page_id"], ["document_pages.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_citations_chunk_id", "citations", ["chunk_id"], unique=False)
    op.create_index("ix_citations_document_id", "citations", ["document_id"], unique=False)
    op.create_index(
        "ix_citations_document_page_id", "citations", ["document_page_id"], unique=False
    )
    op.create_table(
        "compliance_findings",
        sa.Column("finding_code", sa.String(length=120), nullable=False),
        sa.Column("rule_id", sa.Uuid(), nullable=False),
        sa.Column("equipment_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("severity", sa.String(length=40), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("expected_evidence", sa.String(), nullable=True),
        sa.Column("available_evidence", sa.String(), nullable=True),
        sa.Column("missing_evidence", sa.String(), nullable=True),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_notes", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_document_id", sa.Uuid(), nullable=True),
        sa.Column("source_page_id", sa.Uuid(), nullable=True),
        sa.Column("source_chunk_id", sa.Uuid(), nullable=True),
        sa.Column("evidence_span", sa.String(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("extractor_version", sa.String(), nullable=True),
        sa.Column("extracted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata_json", sa.JSON(), server_default="{}", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "severity in ('informational', 'low', 'medium', 'high', 'critical', 'unknown')",
            name="ck_compliance_findings_severity",
        ),
        sa.CheckConstraint(
            "status in ('open', 'acknowledged', 'resolved', 'false_positive')",
            name="ck_compliance_findings_status",
        ),
        sa.CheckConstraint(
            "confidence is null or (confidence >= 0 and confidence <= 1)",
            name="ck_compliance_findings_confidence",
        ),
        sa.CheckConstraint(
            "resolved_at is null or detected_at is null or resolved_at >= detected_at",
            name="ck_compliance_findings_time_order",
        ),
        sa.ForeignKeyConstraint(["equipment_id"], ["equipment.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["rule_id"], ["compliance_rules.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["source_chunk_id"], ["chunks.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_page_id"], ["document_pages.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("finding_code", name="uq_compliance_findings_code"),
    )
    op.create_index(
        "ix_compliance_findings_detected_at", "compliance_findings", ["detected_at"], unique=False
    )
    op.create_index(
        "ix_compliance_findings_equipment_id", "compliance_findings", ["equipment_id"], unique=False
    )
    op.create_index(
        "ix_compliance_findings_rule_id", "compliance_findings", ["rule_id"], unique=False
    )
    op.create_index(
        "ix_compliance_findings_severity", "compliance_findings", ["severity"], unique=False
    )
    op.create_index(
        "ix_compliance_findings_status", "compliance_findings", ["status"], unique=False
    )
    op.create_table(
        "events",
        sa.Column("event_code", sa.String(length=120), nullable=True),
        sa.Column("equipment_id", sa.Uuid(), nullable=False),
        sa.Column("component_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("severity", sa.String(length=40), nullable=False),
        sa.Column("summary", sa.String(length=500), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_document_id", sa.Uuid(), nullable=True),
        sa.Column("source_page_id", sa.Uuid(), nullable=True),
        sa.Column("source_chunk_id", sa.Uuid(), nullable=True),
        sa.Column("evidence_span", sa.String(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("extractor_version", sa.String(), nullable=True),
        sa.Column("extracted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata_json", sa.JSON(), server_default="{}", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_type in ('failure', 'inspection', 'maintenance', 'calibration', 'measurement', 'operational', 'procedure_revision', 'compliance', 'other')",
            name="ck_events_event_type",
        ),
        sa.CheckConstraint(
            "severity in ('informational', 'low', 'medium', 'high', 'critical', 'unknown')",
            name="ck_events_severity",
        ),
        sa.CheckConstraint(
            "status in ('open', 'in_progress', 'closed', 'unknown')", name="ck_events_status"
        ),
        sa.CheckConstraint(
            "confidence is null or (confidence >= 0 and confidence <= 1)",
            name="ck_events_confidence",
        ),
        sa.CheckConstraint(
            "end_time is null or event_time is null or end_time >= event_time",
            name="ck_events_time_order",
        ),
        sa.ForeignKeyConstraint(["component_id"], ["components.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["equipment_id"], ["equipment.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["source_chunk_id"], ["chunks.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_page_id"], ["document_pages.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_code", name="uq_events_event_code"),
    )
    op.create_index("ix_events_component_id", "events", ["component_id"], unique=False)
    op.create_index(
        "ix_events_equipment_time", "events", ["equipment_id", "event_time"], unique=False
    )
    op.create_index("ix_events_event_type", "events", ["event_type"], unique=False)
    op.create_table(
        "graph_edges",
        sa.Column("source_type", sa.String(length=120), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("relationship_type", sa.String(length=120), nullable=False),
        sa.Column("target_type", sa.String(length=120), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), server_default="{}", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_document_id", sa.Uuid(), nullable=True),
        sa.Column("source_page_id", sa.Uuid(), nullable=True),
        sa.Column("source_chunk_id", sa.Uuid(), nullable=True),
        sa.Column("evidence_span", sa.String(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("extractor_version", sa.String(), nullable=True),
        sa.Column("extracted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence is null or (confidence >= 0 and confidence <= 1)",
            name="ck_graph_edges_confidence",
        ),
        sa.ForeignKeyConstraint(["source_chunk_id"], ["chunks.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_page_id"], ["document_pages.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_graph_edges_relationship_type", "graph_edges", ["relationship_type"], unique=False
    )
    op.create_index(
        "ix_graph_edges_source", "graph_edges", ["source_type", "source_id"], unique=False
    )
    op.create_index(
        "ix_graph_edges_target", "graph_edges", ["target_type", "target_id"], unique=False
    )
    op.create_table(
        "procedures",
        sa.Column("procedure_code", sa.String(length=120), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("revision", sa.String(length=80), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_document_id", sa.Uuid(), nullable=True),
        sa.Column("source_page_id", sa.Uuid(), nullable=True),
        sa.Column("source_chunk_id", sa.Uuid(), nullable=True),
        sa.Column("evidence_span", sa.String(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("extractor_version", sa.String(), nullable=True),
        sa.Column("extracted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata_json", sa.JSON(), server_default="{}", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status in ('draft', 'active', 'superseded', 'withdrawn')", name="ck_procedures_status"
        ),
        sa.CheckConstraint(
            "confidence is null or (confidence >= 0 and confidence <= 1)",
            name="ck_procedures_confidence",
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_chunk_id"], ["chunks.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_page_id"], ["document_pages.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("procedure_code", "revision", name="uq_procedures_code_revision"),
    )
    op.create_index("ix_procedures_procedure_code", "procedures", ["procedure_code"], unique=False)
    op.create_index("ix_procedures_status", "procedures", ["status"], unique=False)
    op.create_table(
        "failure_events",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("failure_mode", sa.String(length=160), nullable=False),
        sa.Column("failure_mechanism", sa.String(length=160), nullable=True),
        sa.Column("symptoms_json", sa.JSON(), server_default="[]", nullable=False),
        sa.Column("detected_by", sa.String(length=160), nullable=True),
        sa.Column("downtime_minutes", sa.Integer(), nullable=True),
        sa.Column("production_loss", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("resolution_summary", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "downtime_minutes is null or downtime_minutes >= 0", name="ck_failure_events_downtime"
        ),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", name="uq_failure_events_event_id"),
    )
    op.create_table(
        "maintenance_actions",
        sa.Column("event_id", sa.Uuid(), nullable=True),
        sa.Column("equipment_id", sa.Uuid(), nullable=False),
        sa.Column("component_id", sa.Uuid(), nullable=True),
        sa.Column("procedure_id", sa.Uuid(), nullable=True),
        sa.Column("action_type", sa.String(length=120), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("performed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("performed_by", sa.String(length=160), nullable=True),
        sa.Column("result", sa.String(), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_document_id", sa.Uuid(), nullable=True),
        sa.Column("source_page_id", sa.Uuid(), nullable=True),
        sa.Column("source_chunk_id", sa.Uuid(), nullable=True),
        sa.Column("evidence_span", sa.String(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("extractor_version", sa.String(), nullable=True),
        sa.Column("extracted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata_json", sa.JSON(), server_default="{}", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status in ('planned', 'in_progress', 'completed', 'cancelled', 'unknown')",
            name="ck_maintenance_actions_status",
        ),
        sa.CheckConstraint(
            "confidence is null or (confidence >= 0 and confidence <= 1)",
            name="ck_maintenance_actions_confidence",
        ),
        sa.ForeignKeyConstraint(["component_id"], ["components.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["equipment_id"], ["equipment.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["procedure_id"], ["procedures.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_chunk_id"], ["chunks.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_page_id"], ["document_pages.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_maintenance_actions_equipment_id", "maintenance_actions", ["equipment_id"], unique=False
    )
    op.create_index(
        "ix_maintenance_actions_event_id", "maintenance_actions", ["event_id"], unique=False
    )
    op.create_index(
        "ix_maintenance_actions_performed_at", "maintenance_actions", ["performed_at"], unique=False
    )
    op.create_index(
        "ix_maintenance_actions_procedure_id", "maintenance_actions", ["procedure_id"], unique=False
    )
    op.create_table(
        "measurements",
        sa.Column("equipment_id", sa.Uuid(), nullable=False),
        sa.Column("component_id", sa.Uuid(), nullable=True),
        sa.Column("event_id", sa.Uuid(), nullable=True),
        sa.Column("metric_name", sa.String(length=160), nullable=False),
        sa.Column("metric_value", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("unit", sa.String(length=40), nullable=True),
        sa.Column("measured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("quality", sa.String(length=40), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_document_id", sa.Uuid(), nullable=True),
        sa.Column("source_page_id", sa.Uuid(), nullable=True),
        sa.Column("source_chunk_id", sa.Uuid(), nullable=True),
        sa.Column("evidence_span", sa.String(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("extractor_version", sa.String(), nullable=True),
        sa.Column("extracted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata_json", sa.JSON(), server_default="{}", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quality in ('good', 'suspect', 'bad', 'unknown')", name="ck_measurements_quality"
        ),
        sa.CheckConstraint(
            "confidence is null or (confidence >= 0 and confidence <= 1)",
            name="ck_measurements_confidence",
        ),
        sa.ForeignKeyConstraint(["component_id"], ["components.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["equipment_id"], ["equipment.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_chunk_id"], ["chunks.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_page_id"], ["document_pages.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_measurements_component_id", "measurements", ["component_id"], unique=False)
    op.create_index(
        "ix_measurements_equipment_metric_time",
        "measurements",
        ["equipment_id", "metric_name", "measured_at"],
        unique=False,
    )
    op.create_index("ix_measurements_event_id", "measurements", ["event_id"], unique=False)
    op.create_table(
        "work_orders",
        sa.Column("work_order_number", sa.String(length=120), nullable=False),
        sa.Column("equipment_id", sa.Uuid(), nullable=False),
        sa.Column("component_id", sa.Uuid(), nullable=True),
        sa.Column("event_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("priority", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closure_notes", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_document_id", sa.Uuid(), nullable=True),
        sa.Column("source_page_id", sa.Uuid(), nullable=True),
        sa.Column("source_chunk_id", sa.Uuid(), nullable=True),
        sa.Column("evidence_span", sa.String(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("extractor_version", sa.String(), nullable=True),
        sa.Column("extracted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata_json", sa.JSON(), server_default="{}", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "priority in ('low', 'medium', 'high', 'critical', 'unknown')",
            name="ck_work_orders_priority",
        ),
        sa.CheckConstraint(
            "status in ('open', 'scheduled', 'in_progress', 'completed', 'cancelled', 'unknown')",
            name="ck_work_orders_status",
        ),
        sa.CheckConstraint(
            "completed_at is null or opened_at is null or completed_at >= opened_at",
            name="ck_work_orders_time_order",
        ),
        sa.CheckConstraint(
            "confidence is null or (confidence >= 0 and confidence <= 1)",
            name="ck_work_orders_confidence",
        ),
        sa.ForeignKeyConstraint(["component_id"], ["components.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["equipment_id"], ["equipment.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_chunk_id"], ["chunks.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_page_id"], ["document_pages.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("work_order_number", name="uq_work_orders_number"),
    )
    op.create_index("ix_work_orders_completed_at", "work_orders", ["completed_at"], unique=False)
    op.create_index("ix_work_orders_equipment_id", "work_orders", ["equipment_id"], unique=False)
    op.create_index("ix_work_orders_opened_at", "work_orders", ["opened_at"], unique=False)
    op.create_index("ix_work_orders_priority", "work_orders", ["priority"], unique=False)
    op.create_index("ix_work_orders_scheduled_at", "work_orders", ["scheduled_at"], unique=False)
    op.create_index("ix_work_orders_status", "work_orders", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_work_orders_status", table_name="work_orders")
    op.drop_index("ix_work_orders_scheduled_at", table_name="work_orders")
    op.drop_index("ix_work_orders_priority", table_name="work_orders")
    op.drop_index("ix_work_orders_opened_at", table_name="work_orders")
    op.drop_index("ix_work_orders_equipment_id", table_name="work_orders")
    op.drop_index("ix_work_orders_completed_at", table_name="work_orders")
    op.drop_table("work_orders")
    op.drop_index("ix_measurements_event_id", table_name="measurements")
    op.drop_index("ix_measurements_equipment_metric_time", table_name="measurements")
    op.drop_index("ix_measurements_component_id", table_name="measurements")
    op.drop_table("measurements")
    op.drop_index("ix_maintenance_actions_procedure_id", table_name="maintenance_actions")
    op.drop_index("ix_maintenance_actions_performed_at", table_name="maintenance_actions")
    op.drop_index("ix_maintenance_actions_event_id", table_name="maintenance_actions")
    op.drop_index("ix_maintenance_actions_equipment_id", table_name="maintenance_actions")
    op.drop_table("maintenance_actions")
    op.drop_table("failure_events")
    op.drop_index("ix_procedures_status", table_name="procedures")
    op.drop_index("ix_procedures_procedure_code", table_name="procedures")
    op.drop_table("procedures")
    op.drop_index("ix_graph_edges_target", table_name="graph_edges")
    op.drop_index("ix_graph_edges_source", table_name="graph_edges")
    op.drop_index("ix_graph_edges_relationship_type", table_name="graph_edges")
    op.drop_table("graph_edges")
    op.drop_index("ix_events_event_type", table_name="events")
    op.drop_index("ix_events_equipment_time", table_name="events")
    op.drop_index("ix_events_component_id", table_name="events")
    op.drop_table("events")
    op.drop_index("ix_compliance_findings_status", table_name="compliance_findings")
    op.drop_index("ix_compliance_findings_severity", table_name="compliance_findings")
    op.drop_index("ix_compliance_findings_rule_id", table_name="compliance_findings")
    op.drop_index("ix_compliance_findings_equipment_id", table_name="compliance_findings")
    op.drop_index("ix_compliance_findings_detected_at", table_name="compliance_findings")
    op.drop_table("compliance_findings")
    op.drop_index("ix_citations_document_page_id", table_name="citations")
    op.drop_index("ix_citations_document_id", table_name="citations")
    op.drop_index("ix_citations_chunk_id", table_name="citations")
    op.drop_table("citations")
    op.drop_index("ix_chunks_equipment_id", table_name="chunks")
    op.drop_index("ix_chunks_document_page_id", table_name="chunks")
    op.drop_index("ix_chunks_document_id", table_name="chunks")
    op.drop_index("ix_chunks_chunk_kind", table_name="chunks")
    op.drop_table("chunks")
    op.drop_index("ix_extraction_runs_status", table_name="extraction_runs")
    op.drop_index("ix_extraction_runs_extractor", table_name="extraction_runs")
    op.drop_index("ix_extraction_runs_document_id", table_name="extraction_runs")
    op.drop_table("extraction_runs")
    op.drop_index("ix_document_pages_document_id", table_name="document_pages")
    op.drop_table("document_pages")
    op.drop_index("ix_components_equipment_id", table_name="components")
    op.drop_index("ix_components_component_type", table_name="components")
    op.drop_table("components")
    op.drop_index("ix_ingestion_jobs_status", table_name="ingestion_jobs")
    op.drop_index("ix_ingestion_jobs_started_at", table_name="ingestion_jobs")
    op.drop_table("ingestion_jobs")
    op.drop_index("ix_equipment_site_system", table_name="equipment")
    op.drop_index("ix_equipment_equipment_tag", table_name="equipment")
    op.drop_index("ix_equipment_criticality", table_name="equipment")
    op.drop_index("ix_equipment_class", table_name="equipment")
    op.drop_table("equipment")
    op.drop_index("ix_documents_sha256", table_name="documents")
    op.drop_index("ix_documents_parse_status", table_name="documents")
    op.drop_index("ix_documents_document_code", table_name="documents")
    op.drop_table("documents")
    op.drop_index("ix_compliance_rules_type", table_name="compliance_rules")
    op.drop_index("ix_compliance_rules_enabled", table_name="compliance_rules")
    op.drop_table("compliance_rules")
    # ### end Alembic commands ###
