"""add document ingestion items

Revision ID: 81f572ea2231
Revises: ac38bbf33d78
Create Date: 2026-07-22 07:39:36.909224+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "81f572ea2231"
down_revision: str | None = "ac38bbf33d78"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingestion_items",
        sa.Column("ingestion_job_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=True),
        sa.Column("duplicate_of_document_id", sa.Uuid(), nullable=True),
        sa.Column("original_filename", sa.String(length=512), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("detected_file_type", sa.String(length=80), nullable=True),
        sa.Column("detected_mime_type", sa.String(length=160), nullable=True),
        sa.Column("actual_size_bytes", sa.Integer(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=120), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scanner_status", sa.String(length=120), nullable=True),
        sa.Column("scanner_message", sa.String(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), server_default="{}", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status in ('pending', 'validating', 'stored', 'duplicate', 'failed')",
            name="ck_ingestion_items_status",
        ),
        sa.CheckConstraint(
            "actual_size_bytes is null or actual_size_bytes >= 0", name="ck_ingestion_items_size"
        ),
        sa.CheckConstraint("attempt_count >= 0", name="ck_ingestion_items_attempt_count"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["duplicate_of_document_id"], ["documents.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["ingestion_job_id"], ["ingestion_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ingestion_items_document_id", "ingestion_items", ["document_id"], unique=False
    )
    op.create_index(
        "ix_ingestion_items_job_id", "ingestion_items", ["ingestion_job_id"], unique=False
    )
    op.create_index("ix_ingestion_items_sha256", "ingestion_items", ["sha256"], unique=False)
    op.create_index("ix_ingestion_items_status", "ingestion_items", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ingestion_items_status", table_name="ingestion_items")
    op.drop_index("ix_ingestion_items_sha256", table_name="ingestion_items")
    op.drop_index("ix_ingestion_items_job_id", table_name="ingestion_items")
    op.drop_index("ix_ingestion_items_document_id", table_name="ingestion_items")
    op.drop_table("ingestion_items")
    # ### end Alembic commands ###
